// ISO 3166-1 country list with localized names (ru, en, es) and EU membership flag.

export interface Country {
  code: string; // ISO 3166-1 alpha-2
  en: string;
  es: string;
  ru: string;
}

// EU member states (ISO alpha-2 codes)
export const EU_COUNTRIES = new Set([
  "AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR",
  "DE","GR","HU","IE","IT","LV","LT","LU","MT","NL",
  "PL","PT","RO","SK","SI","ES","SE",
]);

export function isEuCountry(code: string): boolean {
  return EU_COUNTRIES.has(code);
}

export const COUNTRIES: Country[] = [
  { code: "AF", en: "Afghanistan", es: "Afganistán", ru: "Афганистан" },
  { code: "AL", en: "Albania", es: "Albania", ru: "Албания" },
  { code: "DZ", en: "Algeria", es: "Argelia", ru: "Алжир" },
  { code: "AD", en: "Andorra", es: "Andorra", ru: "Андорра" },
  { code: "AO", en: "Angola", es: "Angola", ru: "Ангола" },
  { code: "AG", en: "Antigua and Barbuda", es: "Antigua y Barbuda", ru: "Антигуа и Барбуда" },
  { code: "AR", en: "Argentina", es: "Argentina", ru: "Аргентина" },
  { code: "AM", en: "Armenia", es: "Armenia", ru: "Армения" },
  { code: "AU", en: "Australia", es: "Australia", ru: "Австралия" },
  { code: "AT", en: "Austria", es: "Austria", ru: "Австрия" },
  { code: "AZ", en: "Azerbaijan", es: "Azerbaiyán", ru: "Азербайджан" },
  { code: "BS", en: "Bahamas", es: "Bahamas", ru: "Багамы" },
  { code: "BH", en: "Bahrain", es: "Baréin", ru: "Бахрейн" },
  { code: "BD", en: "Bangladesh", es: "Bangladés", ru: "Бангладеш" },
  { code: "BB", en: "Barbados", es: "Barbados", ru: "Барбадос" },
  { code: "BY", en: "Belarus", es: "Bielorrusia", ru: "Беларусь" },
  { code: "BE", en: "Belgium", es: "Bélgica", ru: "Бельгия" },
  { code: "BZ", en: "Belize", es: "Belice", ru: "Белиз" },
  { code: "BJ", en: "Benin", es: "Benín", ru: "Бенин" },
  { code: "BT", en: "Bhutan", es: "Bután", ru: "Бутан" },
  { code: "BO", en: "Bolivia", es: "Bolivia", ru: "Боливия" },
  { code: "BA", en: "Bosnia and Herzegovina", es: "Bosnia y Herzegovina", ru: "Босния и Герцеговина" },
  { code: "BW", en: "Botswana", es: "Botsuana", ru: "Ботсвана" },
  { code: "BR", en: "Brazil", es: "Brasil", ru: "Бразилия" },
  { code: "BN", en: "Brunei", es: "Brunéi", ru: "Бруней" },
  { code: "BG", en: "Bulgaria", es: "Bulgaria", ru: "Болгария" },
  { code: "BF", en: "Burkina Faso", es: "Burkina Faso", ru: "Буркина-Фасо" },
  { code: "BI", en: "Burundi", es: "Burundi", ru: "Бурунди" },
  { code: "CV", en: "Cabo Verde", es: "Cabo Verde", ru: "Кабо-Верде" },
  { code: "KH", en: "Cambodia", es: "Camboya", ru: "Камбоджа" },
  { code: "CM", en: "Cameroon", es: "Camerún", ru: "Камерун" },
  { code: "CA", en: "Canada", es: "Canadá", ru: "Канада" },
  { code: "CF", en: "Central African Republic", es: "República Centroafricana", ru: "ЦАР" },
  { code: "TD", en: "Chad", es: "Chad", ru: "Чад" },
  { code: "CL", en: "Chile", es: "Chile", ru: "Чили" },
  { code: "CN", en: "China", es: "China", ru: "Китай" },
  { code: "CO", en: "Colombia", es: "Colombia", ru: "Колумбия" },
  { code: "KM", en: "Comoros", es: "Comoras", ru: "Коморы" },
  { code: "CG", en: "Congo", es: "Congo", ru: "Конго" },
  { code: "CD", en: "Congo (DRC)", es: "Congo (RDC)", ru: "ДР Конго" },
  { code: "CR", en: "Costa Rica", es: "Costa Rica", ru: "Коста-Рика" },
  { code: "CI", en: "Côte d'Ivoire", es: "Costa de Marfil", ru: "Кот-д'Ивуар" },
  { code: "HR", en: "Croatia", es: "Croacia", ru: "Хорватия" },
  { code: "CU", en: "Cuba", es: "Cuba", ru: "Куба" },
  { code: "CY", en: "Cyprus", es: "Chipre", ru: "Кипр" },
  { code: "CZ", en: "Czechia", es: "Chequia", ru: "Чехия" },
  { code: "DK", en: "Denmark", es: "Dinamarca", ru: "Дания" },
  { code: "DJ", en: "Djibouti", es: "Yibuti", ru: "Джибути" },
  { code: "DM", en: "Dominica", es: "Dominica", ru: "Доминика" },
  { code: "DO", en: "Dominican Republic", es: "República Dominicana", ru: "Доминиканская Республика" },
  { code: "EC", en: "Ecuador", es: "Ecuador", ru: "Эквадор" },
  { code: "EG", en: "Egypt", es: "Egipto", ru: "Египет" },
  { code: "SV", en: "El Salvador", es: "El Salvador", ru: "Сальвадор" },
  { code: "GQ", en: "Equatorial Guinea", es: "Guinea Ecuatorial", ru: "Экваториальная Гвинея" },
  { code: "ER", en: "Eritrea", es: "Eritrea", ru: "Эритрея" },
  { code: "EE", en: "Estonia", es: "Estonia", ru: "Эстония" },
  { code: "SZ", en: "Eswatini", es: "Esuatini", ru: "Эсватини" },
  { code: "ET", en: "Ethiopia", es: "Etiopía", ru: "Эфиопия" },
  { code: "FJ", en: "Fiji", es: "Fiyi", ru: "Фиджи" },
  { code: "FI", en: "Finland", es: "Finlandia", ru: "Финляндия" },
  { code: "FR", en: "France", es: "Francia", ru: "Франция" },
  { code: "GA", en: "Gabon", es: "Gabón", ru: "Габон" },
  { code: "GM", en: "Gambia", es: "Gambia", ru: "Гамбия" },
  { code: "GE", en: "Georgia", es: "Georgia", ru: "Грузия" },
  { code: "DE", en: "Germany", es: "Alemania", ru: "Германия" },
  { code: "GH", en: "Ghana", es: "Ghana", ru: "Гана" },
  { code: "GR", en: "Greece", es: "Grecia", ru: "Греция" },
  { code: "GD", en: "Grenada", es: "Granada", ru: "Гренада" },
  { code: "GT", en: "Guatemala", es: "Guatemala", ru: "Гватемала" },
  { code: "GN", en: "Guinea", es: "Guinea", ru: "Гвинея" },
  { code: "GW", en: "Guinea-Bissau", es: "Guinea-Bisáu", ru: "Гвинея-Бисау" },
  { code: "GY", en: "Guyana", es: "Guyana", ru: "Гайана" },
  { code: "HT", en: "Haiti", es: "Haití", ru: "Гаити" },
  { code: "HN", en: "Honduras", es: "Honduras", ru: "Гондурас" },
  { code: "HU", en: "Hungary", es: "Hungría", ru: "Венгрия" },
  { code: "IS", en: "Iceland", es: "Islandia", ru: "Исландия" },
  { code: "IN", en: "India", es: "India", ru: "Индия" },
  { code: "ID", en: "Indonesia", es: "Indonesia", ru: "Индонезия" },
  { code: "IR", en: "Iran", es: "Irán", ru: "Иран" },
  { code: "IQ", en: "Iraq", es: "Irak", ru: "Ирак" },
  { code: "IE", en: "Ireland", es: "Irlanda", ru: "Ирландия" },
  { code: "IL", en: "Israel", es: "Israel", ru: "Израиль" },
  { code: "IT", en: "Italy", es: "Italia", ru: "Италия" },
  { code: "JM", en: "Jamaica", es: "Jamaica", ru: "Ямайка" },
  { code: "JP", en: "Japan", es: "Japón", ru: "Япония" },
  { code: "JO", en: "Jordan", es: "Jordania", ru: "Иордания" },
  { code: "KZ", en: "Kazakhstan", es: "Kazajistán", ru: "Казахстан" },
  { code: "KE", en: "Kenya", es: "Kenia", ru: "Кения" },
  { code: "KI", en: "Kiribati", es: "Kiribati", ru: "Кирибати" },
  { code: "KP", en: "North Korea", es: "Corea del Norte", ru: "КНДР" },
  { code: "KR", en: "South Korea", es: "Corea del Sur", ru: "Южная Корея" },
  { code: "KW", en: "Kuwait", es: "Kuwait", ru: "Кувейт" },
  { code: "KG", en: "Kyrgyzstan", es: "Kirguistán", ru: "Киргизия" },
  { code: "LA", en: "Laos", es: "Laos", ru: "Лаос" },
  { code: "LV", en: "Latvia", es: "Letonia", ru: "Латвия" },
  { code: "LB", en: "Lebanon", es: "Líbano", ru: "Ливан" },
  { code: "LS", en: "Lesotho", es: "Lesoto", ru: "Лесото" },
  { code: "LR", en: "Liberia", es: "Liberia", ru: "Либерия" },
  { code: "LY", en: "Libya", es: "Libia", ru: "Ливия" },
  { code: "LI", en: "Liechtenstein", es: "Liechtenstein", ru: "Лихтенштейн" },
  { code: "LT", en: "Lithuania", es: "Lituania", ru: "Литва" },
  { code: "LU", en: "Luxembourg", es: "Luxemburgo", ru: "Люксембург" },
  { code: "MG", en: "Madagascar", es: "Madagascar", ru: "Мадагаскар" },
  { code: "MW", en: "Malawi", es: "Malaui", ru: "Малави" },
  { code: "MY", en: "Malaysia", es: "Malasia", ru: "Малайзия" },
  { code: "MV", en: "Maldives", es: "Maldivas", ru: "Мальдивы" },
  { code: "ML", en: "Mali", es: "Malí", ru: "Мали" },
  { code: "MT", en: "Malta", es: "Malta", ru: "Мальта" },
  { code: "MH", en: "Marshall Islands", es: "Islas Marshall", ru: "Маршалловы Острова" },
  { code: "MR", en: "Mauritania", es: "Mauritania", ru: "Мавритания" },
  { code: "MU", en: "Mauritius", es: "Mauricio", ru: "Маврикий" },
  { code: "MX", en: "Mexico", es: "México", ru: "Мексика" },
  { code: "FM", en: "Micronesia", es: "Micronesia", ru: "Микронезия" },
  { code: "MD", en: "Moldova", es: "Moldavia", ru: "Молдова" },
  { code: "MC", en: "Monaco", es: "Mónaco", ru: "Монако" },
  { code: "MN", en: "Mongolia", es: "Mongolia", ru: "Монголия" },
  { code: "ME", en: "Montenegro", es: "Montenegro", ru: "Черногория" },
  { code: "MA", en: "Morocco", es: "Marruecos", ru: "Марокко" },
  { code: "MZ", en: "Mozambique", es: "Mozambique", ru: "Мозамбик" },
  { code: "MM", en: "Myanmar", es: "Myanmar", ru: "Мьянма" },
  { code: "NA", en: "Namibia", es: "Namibia", ru: "Намибия" },
  { code: "NR", en: "Nauru", es: "Nauru", ru: "Науру" },
  { code: "NP", en: "Nepal", es: "Nepal", ru: "Непал" },
  { code: "NL", en: "Netherlands", es: "Países Bajos", ru: "Нидерланды" },
  { code: "NZ", en: "New Zealand", es: "Nueva Zelanda", ru: "Новая Зеландия" },
  { code: "NI", en: "Nicaragua", es: "Nicaragua", ru: "Никарагуа" },
  { code: "NE", en: "Niger", es: "Níger", ru: "Нигер" },
  { code: "NG", en: "Nigeria", es: "Nigeria", ru: "Нигерия" },
  { code: "MK", en: "North Macedonia", es: "Macedonia del Norte", ru: "Северная Македония" },
  { code: "NO", en: "Norway", es: "Noruega", ru: "Норвегия" },
  { code: "OM", en: "Oman", es: "Omán", ru: "Оман" },
  { code: "PK", en: "Pakistan", es: "Pakistán", ru: "Пакистан" },
  { code: "PW", en: "Palau", es: "Palaos", ru: "Палау" },
  { code: "PS", en: "Palestine", es: "Palestina", ru: "Палестина" },
  { code: "PA", en: "Panama", es: "Panamá", ru: "Панама" },
  { code: "PG", en: "Papua New Guinea", es: "Papúa Nueva Guinea", ru: "Папуа — Новая Гвинея" },
  { code: "PY", en: "Paraguay", es: "Paraguay", ru: "Парагвай" },
  { code: "PE", en: "Peru", es: "Perú", ru: "Перу" },
  { code: "PH", en: "Philippines", es: "Filipinas", ru: "Филиппины" },
  { code: "PL", en: "Poland", es: "Polonia", ru: "Польша" },
  { code: "PT", en: "Portugal", es: "Portugal", ru: "Португалия" },
  { code: "QA", en: "Qatar", es: "Catar", ru: "Катар" },
  { code: "RO", en: "Romania", es: "Rumanía", ru: "Румыния" },
  { code: "RU", en: "Russia", es: "Rusia", ru: "Россия" },
  { code: "RW", en: "Rwanda", es: "Ruanda", ru: "Руанда" },
  { code: "KN", en: "Saint Kitts and Nevis", es: "San Cristóbal y Nieves", ru: "Сент-Китс и Невис" },
  { code: "LC", en: "Saint Lucia", es: "Santa Lucía", ru: "Сент-Люсия" },
  { code: "VC", en: "Saint Vincent and the Grenadines", es: "San Vicente y las Granadinas", ru: "Сент-Винсент и Гренадины" },
  { code: "WS", en: "Samoa", es: "Samoa", ru: "Самоа" },
  { code: "SM", en: "San Marino", es: "San Marino", ru: "Сан-Марино" },
  { code: "ST", en: "São Tomé and Príncipe", es: "Santo Tomé y Príncipe", ru: "Сан-Томе и Принсипи" },
  { code: "SA", en: "Saudi Arabia", es: "Arabia Saudita", ru: "Саудовская Аравия" },
  { code: "SN", en: "Senegal", es: "Senegal", ru: "Сенегал" },
  { code: "RS", en: "Serbia", es: "Serbia", ru: "Сербия" },
  { code: "SC", en: "Seychelles", es: "Seychelles", ru: "Сейшелы" },
  { code: "SL", en: "Sierra Leone", es: "Sierra Leona", ru: "Сьерра-Леоне" },
  { code: "SG", en: "Singapore", es: "Singapur", ru: "Сингапур" },
  { code: "SK", en: "Slovakia", es: "Eslovaquia", ru: "Словакия" },
  { code: "SI", en: "Slovenia", es: "Eslovenia", ru: "Словения" },
  { code: "SB", en: "Solomon Islands", es: "Islas Salomón", ru: "Соломоновы Острова" },
  { code: "SO", en: "Somalia", es: "Somalia", ru: "Сомали" },
  { code: "ZA", en: "South Africa", es: "Sudáfrica", ru: "ЮАР" },
  { code: "SS", en: "South Sudan", es: "Sudán del Sur", ru: "Южный Судан" },
  { code: "ES", en: "Spain", es: "España", ru: "Испания" },
  { code: "LK", en: "Sri Lanka", es: "Sri Lanka", ru: "Шри-Ланка" },
  { code: "SD", en: "Sudan", es: "Sudán", ru: "Судан" },
  { code: "SR", en: "Suriname", es: "Surinam", ru: "Суринам" },
  { code: "SE", en: "Sweden", es: "Suecia", ru: "Швеция" },
  { code: "CH", en: "Switzerland", es: "Suiza", ru: "Швейцария" },
  { code: "SY", en: "Syria", es: "Siria", ru: "Сирия" },
  { code: "TW", en: "Taiwan", es: "Taiwán", ru: "Тайвань" },
  { code: "TJ", en: "Tajikistan", es: "Tayikistán", ru: "Таджикистан" },
  { code: "TZ", en: "Tanzania", es: "Tanzania", ru: "Танзания" },
  { code: "TH", en: "Thailand", es: "Tailandia", ru: "Таиланд" },
  { code: "TL", en: "Timor-Leste", es: "Timor Oriental", ru: "Восточный Тимор" },
  { code: "TG", en: "Togo", es: "Togo", ru: "Того" },
  { code: "TO", en: "Tonga", es: "Tonga", ru: "Тонга" },
  { code: "TT", en: "Trinidad and Tobago", es: "Trinidad y Tobago", ru: "Тринидад и Тобаго" },
  { code: "TN", en: "Tunisia", es: "Túnez", ru: "Тунис" },
  { code: "TR", en: "Turkey", es: "Turquía", ru: "Турция" },
  { code: "TM", en: "Turkmenistan", es: "Turkmenistán", ru: "Туркменистан" },
  { code: "TV", en: "Tuvalu", es: "Tuvalu", ru: "Тувалу" },
  { code: "UG", en: "Uganda", es: "Uganda", ru: "Уганда" },
  { code: "UA", en: "Ukraine", es: "Ucrania", ru: "Украина" },
  { code: "AE", en: "United Arab Emirates", es: "Emiratos Árabes Unidos", ru: "ОАЭ" },
  { code: "GB", en: "United Kingdom", es: "Reino Unido", ru: "Великобритания" },
  { code: "US", en: "United States", es: "Estados Unidos", ru: "США" },
  { code: "UY", en: "Uruguay", es: "Uruguay", ru: "Уругвай" },
  { code: "UZ", en: "Uzbekistan", es: "Uzbekistán", ru: "Узбекистан" },
  { code: "VU", en: "Vanuatu", es: "Vanuatu", ru: "Вануату" },
  { code: "VA", en: "Vatican City", es: "Ciudad del Vaticano", ru: "Ватикан" },
  { code: "VE", en: "Venezuela", es: "Venezuela", ru: "Венесуэла" },
  { code: "VN", en: "Vietnam", es: "Vietnam", ru: "Вьетнам" },
  { code: "YE", en: "Yemen", es: "Yemen", ru: "Йемен" },
  { code: "ZM", en: "Zambia", es: "Zambia", ru: "Замбия" },
  { code: "ZW", en: "Zimbabwe", es: "Zimbabue", ru: "Зимбабве" },
];

// Country names are localized in ru/en/es only. For other UI languages
// (e.g. Ukrainian) we fall back to English.
export function countryNameKey(lang: string): "ru" | "en" | "es" {
  return lang === "ru" || lang === "es" ? lang : "en";
}

export function countryName(code: string, lang: string): string {
  const c = COUNTRIES.find((c) => c.code === code);
  if (!c) return code;
  return c[countryNameKey(lang)] || c.en;
}
