/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalNoticeRouteImport } from './routes/legal.notice'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as AppSummaryRouteImport } from './routes/_app.summary'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppDownloadRouteImport } from './routes/_app.download'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app.documents.index'
import { Route as AppDocumentsNewRouteImport } from './routes/_app.documents.new'
import { Route as AppDocumentsIdRouteImport } from './routes/_app.documents.$id'
import { Route as ApiOauthGmailStartRouteImport } from './routes/api/oauth/gmail/start'
import { Route as ApiOauthGmailCallbackRouteImport } from './routes/api/oauth/gmail/callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal/notice',
  path: '/legal/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSummaryRoute = AppSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadRoute = AppDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsNewRoute = AppDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiOauthGmailStartRoute = ApiOauthGmailStartRouteImport.update({
  id: '/api/oauth/gmail/start',
  path: '/api/oauth/gmail/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGmailCallbackRoute = ApiOauthGmailCallbackRouteImport.update({
  id: '/api/oauth/gmail/callback',
  path: '/api/oauth/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/clients': typeof AppClientsRoute
  '/download': typeof AppDownloadRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/summary': typeof AppSummaryRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/notice': typeof LegalNoticeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
  '/api/oauth/gmail/start': typeof ApiOauthGmailStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/clients': typeof AppClientsRoute
  '/download': typeof AppDownloadRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/summary': typeof AppSummaryRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/notice': typeof LegalNoticeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
  '/api/oauth/gmail/start': typeof ApiOauthGmailStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/download': typeof AppDownloadRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/summary': typeof AppSummaryRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/notice': typeof LegalNoticeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_app/documents/$id': typeof AppDocumentsIdRoute
  '/_app/documents/new': typeof AppDocumentsNewRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
  '/api/oauth/gmail/start': typeof ApiOauthGmailStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/clients'
    | '/download'
    | '/services'
    | '/settings'
    | '/summary'
    | '/legal/cookies'
    | '/legal/notice'
    | '/legal/privacy'
    | '/legal/terms'
    | '/documents/$id'
    | '/documents/new'
    | '/documents/'
    | '/api/oauth/gmail/callback'
    | '/api/oauth/gmail/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/clients'
    | '/download'
    | '/services'
    | '/settings'
    | '/summary'
    | '/legal/cookies'
    | '/legal/notice'
    | '/legal/privacy'
    | '/legal/terms'
    | '/documents/$id'
    | '/documents/new'
    | '/documents'
    | '/api/oauth/gmail/callback'
    | '/api/oauth/gmail/start'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/clients'
    | '/_app/download'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/summary'
    | '/legal/cookies'
    | '/legal/notice'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_app/documents/$id'
    | '/_app/documents/new'
    | '/_app/documents/'
    | '/api/oauth/gmail/callback'
    | '/api/oauth/gmail/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiOauthGmailCallbackRoute: typeof ApiOauthGmailCallbackRoute
  ApiOauthGmailStartRoute: typeof ApiOauthGmailStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/notice': {
      id: '/legal/notice'
      path: '/legal/notice'
      fullPath: '/legal/notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/summary': {
      id: '/_app/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AppSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/download': {
      id: '/_app/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof AppDownloadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/new': {
      id: '/_app/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AppDocumentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/$id': {
      id: '/_app/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/oauth/gmail/start': {
      id: '/api/oauth/gmail/start'
      path: '/api/oauth/gmail/start'
      fullPath: '/api/oauth/gmail/start'
      preLoaderRoute: typeof ApiOauthGmailStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/gmail/callback': {
      id: '/api/oauth/gmail/callback'
      path: '/api/oauth/gmail/callback'
      fullPath: '/api/oauth/gmail/callback'
      preLoaderRoute: typeof ApiOauthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDownloadRoute: typeof AppDownloadRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSummaryRoute: typeof AppSummaryRoute
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
  AppDocumentsNewRoute: typeof AppDocumentsNewRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppClientsRoute: AppClientsRoute,
  AppDownloadRoute: AppDownloadRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSummaryRoute: AppSummaryRoute,
  AppDocumentsIdRoute: AppDocumentsIdRoute,
  AppDocumentsNewRoute: AppDocumentsNewRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiOauthGmailCallbackRoute: ApiOauthGmailCallbackRoute,
  ApiOauthGmailStartRoute: ApiOauthGmailStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
